name: Build Docker images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [12, 13, 15, 16]
    env:
      repo: "govpf/postgres"
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Build and push
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./${{ matrix.versions }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: false
        tags: |
          ${{ env.repo }}:${{ matrix.versions }}
